Election-main/fstCopy_Proj5/fstCopy_Proj5/Models/USER.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fstCopy_Proj5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID { get; set; }
        public string NationalNumber { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string FullName { get; set; }
        public string ElectionArea { get; set; }
        public string Governorate { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Gender { get; set; }
        public Nullable<bool> LocalElections { get; set; }
        public Nullable<bool> PartyElections { get; set; }
        public Nullable<bool> whitePaperLocalElections { get; set; }
        public Nullable<bool> whitePaperPartyElections { get; set; }
        public string PlaceOfResidence { get; set; }
        public string NameOftheStation { get; set; }
        public string FundNumber { get; set; }
    }
}

Election-main/fstCopy_Proj5/fstCopy_Proj5/Controllers/USERController.cs
using System;
using System.Linq;
using System.Net.Mail;
using System.Net;
using System.Text;
using System.Web.Mvc;
using Newtonsoft.Json;
using fstCopy_Proj5.Models;

namespace E_Voting.Controllers
{
    public class USERController : Controller
    {
        private ElectionEntities DB = new ElectionEntities();

        // GET: USER
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Logout()
        {
            return RedirectToAction("Index");
        }

        public ActionResult Login(User user)
        {
            try
            {
                if (user == null)
                {
                    ModelState.AddModelError("", "User not found.");
                    return View();
                }

                var existingUser = DB.Users.FirstOrDefault(u => u.NationalNumber == user.NationalNumber);

                if (existingUser == null)
                {
                    ModelState.AddModelError("", "");
                    return View();
                }

                if (existingUser.Password == "password")
                {
                    string newPassword = GenerateRandomPassword();
                    existingUser.Password = newPassword;
                    DB.SaveChanges();

                    SendConfirmationEmail(existingUser.Email, newPassword);

                    ViewBag.Emailsent = "The code has been sent to your Email";
                }

                // تخزين المستخدم في الجلسة وإعادة التوجيه إلى LoginUser
                Session["LoggedUser"] = JsonConvert.SerializeObject(existingUser);
                return RedirectToAction("LoginUser", new { ID = user.ID });
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "An error occurred while processing your request. Please try again later.");
                Console.WriteLine("Exception message: " + ex.Message);
            }

            return View();
        }

        public ActionResult LoginUser(string nationalNumber)
        {
            var user = DB.Users.FirstOrDefault(u => u.NationalNumber == nationalNumber);

            if (user == null)
            {
                ModelState.AddModelError("", "");
                return View();
            }

            // Save in session
            Session["LoggedUser"] = JsonConvert.SerializeObject(user);
            ViewBag.NationalNumber = nationalNumber;
            ViewBag.Email = user.Email;

            // Redirect to the new page with buttons
            return RedirectToAction("ElectionDistricts");
        }


        //Generate password
        private string GenerateRandomPassword()
        {
            const string valid = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890";
            StringBuilder res = new StringBuilder();
            Random rnd = new Random();
            int length = 8;
            while (0 < length--)
            {
                res.Append(valid[rnd.Next(valid.Length)]);
            }
            return res.ToString();
        }

        // Send Email
        private void SendConfirmationEmail(string toEmail, string confirmationCode)
        {
            string fromEmail = "teamorange077@gmail.com";
            string smtpUsername = "teamorange077@gmail.com";
            string smtpPassword = "thxc lkmk weir bxbq";
            //Credentials = new NetworkCredential("teamorange077@gmail.com", "thxc lkmk weir bxbq"),


            string subjectText = "Your Confirmation Code";
            string messageText = $"Your confirmation code is {confirmationCode}";

            string smtpServer = "smtp.gmail.com";
            int smtpPort = 587;

            using (MailMessage mailMessage = new MailMessage())
            {
                mailMessage.From = new MailAddress(fromEmail);
                mailMessage.To.Add(toEmail);
                mailMessage.Subject = subjectText;
                mailMessage.Body = messageText;
                mailMessage.IsBodyHtml = false;

                using (SmtpClient smtpClient = new SmtpClient(smtpServer, smtpPort))
                {
                    smtpClient.UseDefaultCredentials = false;
                    smtpClient.Credentials = new NetworkCredential(smtpUsername, smtpPassword);
                    smtpClient.EnableSsl = true;

                    smtpClient.Send(mailMessage);
                }
            }
        }

        public ActionResult TypeOfElection(int id)
        {
            var user = DB.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }

            // Save the user to the session
            Session["LoggedUser"] = JsonConvert.SerializeObject(user);
            ViewBag.NationalNumber = user.NationalNumber;

            // Determine the paths for elections
            ViewBag.LocalElectionsPath = (bool)user.LocalElections ? null : "LocalElections";
            ViewBag.PartyElectionsPath = (bool)user.PartyElections ? null : "PartyElections";

            return View();
        }



        public ActionResult LocalElections()
        {
            if (Session["LoggedUser"] == null)
            {
                return RedirectToAction("Login");
            }

            var userJson = Session["LoggedUser"].ToString();
            var user = JsonConvert.DeserializeObject<User>(userJson);

            ViewBag.UserId = user.ID;

            var localLists = DB.LocalLists.Where(l => l.ElectionArea == user.ElectionArea).ToList();
            var candidates = DB.LocalListCandidates.ToList();

            ViewBag.LocalLists = localLists;
            ViewBag.Candidates = candidates;

            return View();
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LocalElections(int selectedListId, int[] selectedCandidateIds)
        {
            if (Session["LoggedUser"] == null)
            {
                return RedirectToAction("Login");
            }

            var userJson = Session["LoggedUser"].ToString();
            var user = JsonConvert.DeserializeObject<User>(userJson);

            var selectedList = DB.LocalLists.Find(selectedListId);

            if (selectedList != null && selectedCandidateIds != null)
            {
                if (selectedList.NumberOfVotes == null)
                {
                    selectedList.NumberOfVotes = 0;
                }
                // Update the number of votes for the selected list
                selectedList.NumberOfVotes += 1;
                DB.Entry(selectedList).State = System.Data.Entity.EntityState.Modified;

                // Update the number of votes for the selected candidates
                foreach (var candidateId in selectedCandidateIds)
                {
                    var selectedCandidate = DB.LocalListCandidates.FirstOrDefault(c => c.CandidateID == candidateId && c.LocalListingID == selectedListId);
                    if (selectedCandidate != null)
                    {
                        if (selectedCandidate.NumberOfVotesCandidate == null)
                        {
                            selectedCandidate.NumberOfVotesCandidate = 0;
                        }
                        selectedCandidate.NumberOfVotesCandidate += 1;
                        DB.Entry(selectedCandidate).State = System.Data.Entity.EntityState.Modified;
                    }
                }

                // Update user table to reflect that the user has voted in local elections
                user.LocalElections = true;
                DB.Entry(user).State = System.Data.Entity.EntityState.Modified;

                DB.SaveChanges();
            }

            return RedirectToAction("TypeOfElection", new { id = user.ID });
        }


        public ActionResult PartyElections()
        {
            if (Session["LoggedUser"] == null)
            {
                return RedirectToAction("Login");
            }

            var userJson = Session["LoggedUser"].ToString();
            var user = JsonConvert.DeserializeObject<User>(userJson);

            ViewBag.UserId = user.ID;

            // Retrieve all party lists to display in the view
            var partyLists = DB.GeneralListings.ToList();
            return View(partyLists);
        }

        [HttpPost]
        public ActionResult PartyElections(int selectedPartyListId)
        {
            if (Session["LoggedUser"] == null)
            {
                return RedirectToAction("Login");
            }

            var userJson = Session["LoggedUser"].ToString();
            var user = JsonConvert.DeserializeObject<User>(userJson);

            var selectedPartyList = DB.GeneralListings.Where(x=> x.GeneralListingID  == selectedPartyListId).FirstOrDefault();
            if (selectedPartyList != null)
            {
                // Update user table to reflect that the user has voted in party elections
                user.PartyElections = true;
                //user.LocalElections = true; // Optionally, you can set LocalElections to true here if needed
                if (selectedPartyList.NumberOfVotes == null)
                {
                    selectedPartyList.NumberOfVotes = 0;
                }
                // Update the party list to increment the number of votes
                selectedPartyList.NumberOfVotes += 1;
                DB.Entry(selectedPartyList).State = System.Data.Entity.EntityState.Modified;
                DB.Entry(user).State = System.Data.Entity.EntityState.Modified; // Ensure user entity is being tracked
                DB.SaveChanges();
            }

            return RedirectToAction("TypeOfElection", new { id = user.ID });
        }


        //////////////////////////////////////////////////////////////////////////////////////////////////////////
        ///
        public ActionResult ElectionDistricts()
        {

Election-main/fstCopy_Proj5/fstCopy_Proj5/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using fstCopy_Proj5.Models;

namespace fstCopy_Proj5.Controllers
{
    public class UsersController : Controller
    {
        private ElectionEntities db = new ElectionEntities();

        // GET: Users
        public ActionResult Index()
        {
            return View(db.Users.ToList());
        }

        // GET: Users/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: Users/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,NationalNumber,Email,Password,FullName,ElectionArea,Governorate,BirthDate,Gender,LocalElections,PartyElections,whitePaperLocalElections,whitePaperPartyElections")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Users.Add(user);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(user);
        }

        // GET: Users/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,NationalNumber,Email,Password,FullName,ElectionArea,Governorate,BirthDate,Gender,LocalElections,PartyElections,whitePaperLocalElections,whitePaperPartyElections")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            User user = db.Users.Find(id);
            db.Users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Election-main/fstCopy_Proj5/fstCopy_Proj5/Views/USER/ElectionDistricts.cshtml
@{
    ViewBag.Title = "Election Districts";
    string electionArea = ViewBag.ElectionArea;
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<div style="display: flex; flex-direction: column; justify-content: center;">
    <h2 class="text-center mb-5">اختيار الدائرة الانتخابية</h2>

    <div class="container">
        <div class="row">
            <!-- Card for Irbed First District -->
            <div class="col-md-4 mb-4">
                <div class="card election-card @(electionArea == "اربد الأولى" ? "active" : "")" style="width: 22rem;">
                    <img src="~/images/irbid1.jpg" class="card-img-top" alt="دائرة اربد الأولى">
                    <div class="card-body">
                        <h5 class="card-title">دائرة اربد الأولى</h5>
                        <button type="button" class="btn btn-light btn-block"
                                onclick="location.href='@Url.Action("IrbedFirstDistrict", "USER")'"
                                @(electionArea == "اربد الأولى" ? "" : "disabled")>
                            الدخول إلى دائرة اربد الأولى
                        </button>
                    </div>
                </div>
            </div>

            <!-- Card for Irbed Second District -->
            <div class="col-md-4 mb-4">
                <div class="card election-card @(electionArea == "اربد الثانية" ? "active" : "")" style="width: 22rem ">
                    <img src="~/images/irbid2.jpg" class="card-img-top" alt="دائرة اربد الثانية">
                    <div class="card-body">
                        <h5 class="card-title">دائرة اربد الثانية</h5>
                        <button type="button" class="btn btn-light btn-block"
                                onclick="location.href='@Url.Action("IrbedSecondDistrict", "USER")'"
                                @(electionArea == "اربد الثانية" ? "" : "disabled")>
                            الدخول إلى دائرة اربد الثانية
                        </button>
                    </div>
                </div>
            </div>

            <!-- Card for Ajloun District -->
            <div class="col-md-4 mb-4">
                <div class="card election-card @(electionArea == "عجلون" ? "active" : "")" style="width: 22rem">
                    <img src="~/images/Ajlon.jpg" class="card-img-top" alt="دائرة عجلون">
                    <div class="card-body">
                        <h5 class="card-title">دائرة عجلون</h5>
                        <button type="button" class="btn btn-light btn-block"
                                onclick="location.href='@Url.Action("AjlounDistrict", "USER")'"
                                @(electionArea == "عجلون" ? "" : "disabled")>
                            الدخول إلى دائرة عجلون
                        </button>
                    </div>
                </div>
            </div>

            <!-- Example of Disabled Card -->
            <div class="col-md-4 mb-4">
                <div class="card election-card" style="width: 22rem;">
                    <img src="~/images/amman1.jpg" class="card-img-top" alt="دائرة غير مفعلة">
                    <div class="card-body disabled">
                        <h5 class="card-title disabled">دائرة عمان</h5>
                        <button type="button" class="btn btn-light btn-block disabled">
                            الدخول إلى دائرة عمان الأولى
                        </button>
                    </div>
                </div>
            </div>
            <!-- Repeat the disabled card as needed -->
            <div class="col-md-4 mb-4">
                <div class="card election-card" style="width: 22rem;">
                    <img src="~/images/Amman2.jpg" class="card-img-top" alt="دائرة غير مفعلة">
                    <div class="card-body disabled">
                        <h5 class="card-title disabled">دائرة عمان</h5>
                        <button type="button" class="btn btn-light btn-block disabled">
                            الدخول إلى دائرة عمان الثانية
                        </button>
                    </div>
                </div>
            </div>
            <div class="col-md-4 mb-4">
                <div class="card election-card" style="width: 22rem;">
                    <img src="~/images/Amman3.jpg" class="card-img-top" alt="دائرة غير مفعلة">
                    <div class="card-body disabled">
                        <h5 class="card-title disabled">دائرة عمان</h5>
                        <button type="button" class="btn btn-light btn-block disabled">
                            الدخول إلى دائرة عمان الثالثة
                        </button>
                    </div>
                </div>
            </div>

            <div class="col-md-4 mb-4">
                <div class="card election-card" style="width: 22rem;">
                    <img src="~/images/As-salt.jpg" class="card-img-top" alt="دائرة غير مفعلة">
                    <div class="card-body disabled">
                        <h5 class="card-title disabled">دائرة السلط</h5>
                        <button type="button" class="btn btn-light btn-block disabled">
                            الدخول إلى دائرة السلط
                        </button>
                    </div>
                </div>
            </div>

            <div class="col-md-4 mb-4">
                <div class="card election-card" style="width: 22rem;">
                    <img src="~/images/karak.jpg" class="card-img-top" alt="دائرة غير مفعلة">
                    <div class="card-body disabled">
                        <h5 class="card-title disabled">دائرة الكرك</h5>
                        <button type="button" class="btn btn-light btn-block disabled">
                            الدخول إلى دائرة الكرك
                        </button>
                    </div>
                </div>
            </div>

            <div class="col-md-4 mb-4">
                <div class="card election-card" style="width: 22rem;">
                    <img src="~/images/jarash.jpg" class="card-img-top" alt="دائرة غير مفعلة">
                    <div class="card-body disabled">
                        <h5 class="card-title disabled">دائرة جرش</h5>
                        <button type="button" class="btn btn-light btn-block disabled">
                            الدخول إلى دائرة جرش
                        </button>
                    </div>
                </div>
            </div>

            <div class="col-md-4 mb-4">
                <div class="card election-card" style="width: 22rem;">
                    <img src="~/images/petra.jpg" class="card-img-top" alt="دائرة غير مفعلة">
                    <div class="card-body disabled">
                        <h5 class="card-title disabled">دائرة معان</h5>
                        <button type="button" class="btn btn-light btn-block disabled">
                            الدخول إلى دائرة معان
                        </button>
                    </div>
                </div>
            </div>

            <div class="col-md-4 mb-4">
                <div class="card election-card" style="width: 22rem;">
                    <img src="~/images/aqaba.jpg" class="card-img-top" alt="دائرة غير مفعلة">
                    <div class="card-body disabled">
                        <h5 class="card-title disabled">دائرة العقبة</h5>
                        <button type="button" class="btn btn-light btn-block disabled">
                            الدخول إلى دائرة العقبة
                        </button>
                    </div>
                </div>
            </div>

            <div class="col-md-4 mb-4">
                <div class="card election-card" style="width: 22rem;">
                    <img src="~/images/Mafraq.jpg" class="card-img-top" alt="دائرة غير مفعلة">
                    <div class="card-body disabled">
                        <h5 class="card-title disabled">دائرة المفرق</h5>
                        <button type="button" class="btn btn-light btn-block disabled">
                            الدخول إلى دائرة المفرق
                        </button>
                    </div>
                </div>
            </div>


        </div>
    </div>
</div>

<style>
    .election-card {
        background-color: #fff; /* Red background */
        color: #fff; /* White text */
        border: none;
        border-radius: 8px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 1);
        transition: transform 0.3s ease, box-shadow 0.3s ease;
        margin: 10px;
    }

        .election-card:hover {
            transform: translateY(-5px);
            box-shadow: 0 8px 16px rgba(0, 0, 0, 0.2);
        }

    .card-img-top {
        border-top-left-radius: 8px;
        border-top-right-radius: 8px;
        width: 100%;
        height: 180px; /* Fixed height for images */
        object-fit: cover;
    }

    .card-body {
        text-align: center; /* Center align text */
        padding: 1.25rem; /* Adjust padding to fit the card */
    }

    .card-title {
        font-size: 18px; /* Adjust title size */
        margin-bottom: 10px;
    }

    .btn-light {
        background-color: #fff;
        color: #dc3545;
        border: none;
        border-radius: 5px;
    }

        .btn-light:disabled {
            background-color: #f8f9fa;
            color: #dc3545;
        }
</style>

Election-main/fstCopy_Proj5/fstCopy_Proj5/Views/USER/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";

}

<h2>Index</h2>

<p>Welcome to the E-Voting system.</p>
<a href="@Url.Action("Login", "User")">Login</a>

Election-main/fstCopy_Proj5/fstCopy_Proj5/Views/USER/LocalElections.cshtml
@{
    ViewBag.Title = "Local Elections";
    var localLists = ViewBag.LocalLists as List<fstCopy_Proj5.Models.LocalList>;
    var candidates = ViewBag.Candidates as List<fstCopy_Proj5.Models.LocalListCandidate>;
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
<body>

    <div style="padding-top: 85px; padding-bottom: 85px">

        @using (Html.BeginForm("LocalElections", "User", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            <div style="display: flex; flex-direction: row; justify-content: space-evenly; align-content:center; ">

                <div class="row">
                    <h2 style="text-align : center">.أهلا بك في صفحة القوائم المحلية</h2>

                    @if (localLists != null && localLists.Any())
                    {
                        foreach (var list in localLists)
                        {
                            <div class="col-md-4 mb-4">
                                <div class="card election-card" style="width: 18rem;">
                                    <img src="~/images/localParty.jpg" class="card-img-top" alt="Party Image">
                                    <div class="card-body">
                                        <h5 class="card-title">اسم القائمه :  @list.ListName </h5>
                                        <p class="card-text">
                                            الدائرة : @list.ElectionArea<br />
                                            المحافظة : @list.Governorate
                                        </p>
                                        <div class="form-check">
                                            <input class="form-check-input" type="radio" name="selectedListId" value="@list.ID" id="list@list.ID">
                                            <label class="form-check-label" for="list@list.ID">
                                                @list.ListName
                                            </label>
                                        </div>
                                        <p>
                                            <strong>المرشحين :</strong><br />
                                            @foreach (var candidate in candidates.Where(c => c.LocalListingID == list.ID))
                                            {
                                                <div class="form-check">
                                                    <input class="form-check-input" type="checkbox" name="selectedCandidateIds" value="@candidate.CandidateID" id="candidate@candidate.CandidateID">
                                                    <label class="form-check-label" for="candidate@candidate.CandidateID">
                                                        @candidate.CandidateName
                                                    </label>
                                                </div>
                                            }
                                        </p>
                                    </div>
                                    <br />
                                </div>
                            </div>
                        }
                    }
                    else
                    {
                        <p>No lists available for your election area.</p>
                    }
                </div>
            </div>
            <button type="submit" class="btn btn-primary" onclick="return confirmSubmission();">تأكيد التصويت</button>
        }
    </div>
</body>
<script>
    function confirmSubmission() {
        return confirm("هل أنت متأكد من التصويت؟");
    }
</script>

<style>
    body {
        direction: rtl;
    }

    .election-card {
        background-color: #fff; /* White background */
        color: rgba(0, 0, 0, 1); /* Black text */
        border: none;
        border-radius: 8px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 1);
        transition: transform 0.3s ease, box-shadow 0.3s ease;
        margin: 5rem;
    }

    .card-body {
        text-align: right !important;
        padding-right: 1rem;
        height: 20rem;
    }

    .election-card:hover {
        transform: translateY(-5px);
        box-shadow: 0 8px 16px rgba(0, 0, 0, 0.2);
    }

    .card-img-top {
        border-top-left-radius: 8px;
        border-top-right-radius: 8px;
        width: 100%;
        height: 180px; /* Fixed height for images */
        object-fit: cover;
    }

    .card-body {
        text-align: center; /* Center align text */
        padding: 1.25rem; /* Adjust padding to fit the card */
    }

    .card-title {
        font-size: 18px; /* Adjust title size */
        margin-bottom: 10px;
    }

    .btn-light {
        background-color: #fff;
        color: #dc3545; /* Red text */
        border: none;
        border-radius: 5px;
    }

        .btn-light:disabled {
            background-color: #f8f9fa;
            color: #dc3545;
        }

    .row {
        /* margin-right: -15px; */
        margin-left: 92px;
    }
    .btn-primary {
        color: #fff;
        background-color: #337ab7;
        border-color: #2e6da4;
        margin-right: 40rem;
    }
</style>